# Etapa 1: Escolha uma imagem base com o JDK adequado
FROM openjdk:17-jdk-slim as build

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o arquivo JAR gerado para o diretório de trabalho no container
COPY target/*.jar app.jar

# Comando para rodar a aplicação Spring Boot
ENTRYPOINT ["java", "-jar", "/app/app.jar"]

# Exponha a porta que a aplicação estará rodando
EXPOSE 8080